AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS Serverless Application

  Sample SAM Template for AWS Serverless Application

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  OAuth2AuthorizationEndpoint:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/identity-1.0.jar
      Handler: api.oauth2.endpoints.Authorization::handleRequest
      Runtime: java8
      Events:
        PostRequest:
          Type: Api
          Properties:
            Path: /oauth2/authorize
            Method: GET

  OAuth2TokenEndpoint:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/identity-1.0.jar
      Handler: api.oauth2.endpoints.Token::handleRequest
      Runtime: java8
      Events:
        PostRequest:
          Type: Api
          Properties:
            Path: /oauth2/token
            Method: POST

  OpenIDUserInfoEndpoint:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/identity-1.0.jar
      Handler: api.openid.endpoints.UserInfo::handleRequest
      Runtime: java8
      Events:
        PostRequest:
          Type: Api
          Properties:
            Path: /openid/user_info
            Method: GET

  OpenIDConfiguration:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/identity-1.0.jar
      Handler: api.openid.endpoints.Configuration::handleRequest
      Runtime: java8
      Events:
        PostRequest:
          Type: Api
          Properties:
            Path: /.well-known/openid-configuration
            Method: GET

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  OAuth2AuthorizationEndpoint:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt OAuth2AuthorizationEndpoint.Arn
  OAuth2AuthorizationEndpointIamRole:
    Description: "Implicit IAM Role created for endpoint"
    Value: !GetAtt OAuth2AuthorizationEndpointRole.Arn
